version: '3.8'

services:
  app:
    image: loop9/chatbot-lfimoveis:latest
    environment:
      - PORT=8000
      - TZ=America/Sao_Paulo
    env_file:
      - .env
    networks:
      - loop9Net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        # Traefik
        - "traefik.enable=true"

        # Router HTTP (redirect to HTTPS)
        - "traefik.http.routers.chatbot-lfimoveis-http.rule=Host(`lfimoveis.loop9.com.br`)"
        - "traefik.http.routers.chatbot-lfimoveis-http.entrypoints=web"
        - "traefik.http.routers.chatbot-lfimoveis-http.middlewares=redirect-to-https"

        # Router HTTPS
        - "traefik.http.routers.chatbot-lfimoveis.rule=Host(`lfimoveis.loop9.com.br`)"
        - "traefik.http.routers.chatbot-lfimoveis.entrypoints=websecure"
        - "traefik.http.routers.chatbot-lfimoveis.tls.certresolver=letsencrypt"

        # Service
        - "traefik.http.services.chatbot-lfimoveis.loadbalancer.server.port=8000"

        # Middleware redirect
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

networks:
  loop9Net:
    external: true
